In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
sns.set_style("whitegrid")
import matplotlib.pyplot as plt
%matplotlib inline

import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [11]:
df = pd.read_csv('sample_data/messy_daily_website_visitors.csv')

df.rename(columns = {
    'Day.Of.Week' : 'day_of_week',
    'Page.Loads' : 'page_loads',
    'Unique.Visits' : 'unique_visits',
    'First.Time.Visits' : 'first_visits',
    'Returning.Visits' : 'returning_visits'
}, inplace = True)

df = df.replace(',', '', regex=True)

df['page_loads'] = df['page_loads'].fillna(0).astype(int)
df['unique_visits'] = df['unique_visits'].fillna(0).astype(int)
df['first_visits'] = df['first_visits'].fillna(0).astype(int)
df['returning_visits'] = df['returning_visits'].fillna(0).astype(int)

df

,Row,Day,day_of_week,Date,page_loads,unique_visits,first_visits,returning_visits
0,1.0,Sunday,1,9/14/2014,2146,1582,1430,152
1,2.0,Monday,2,9/15/2014,3621,2528,2297,231
2,3.0,Tuesday,3,9/16/2014,3698,2630,2352,278
3,4.0,Wednesday,4,9/17/2014,3667,2614,2327,287
4,5.0,Thursday,5,9/18/2014,3316,2366,2130,236
...,...,...,...,...,...,...,...,...
2162,2163.0,Saturday,7,8/15/2020,2221,1696,1373,323
2163,2164.0,Sunday,1,8/16/2020,2724,2037,1686,351
2164,2165.0,Monday,2,8/17/2020,3456,2638,2181,457
2165,2166.0,Tuesday,3,8/18/2020,3581,2683,2184,499
2166,2167.0,Wednesday,4,8/19/2020,2064,1564,1297,267

In [10]:
# a. Berapa total returning visits dan nilai rata-rata dari unique visits setelah data dibersihkan?
# Menghitung total returning visits
total_returning_visits = df['returning_visits'].sum()

# Menghitung rata-rata dari unique visits
average_unique_visits = df['unique_visits'].mean()

total_returning_visits, average_unique_visits

(1098416, 2943.6465159206277)

In [8]:
# b. Menghitung rata-rata jumlah page loads untuk setiap unique visits
average_page_loads_per_unique_visit = df['page_loads'].sum() / df['unique_visits'].sum()

average_page_loads_per_unique_visit

1.3853016876625088

In [9]:
# c. Menghitung jumlah page loads per hari (berdasarkan 'day_of_week')
page_loads_per_day = df.groupby('day_of_week')['page_loads'].sum()

page_loads_per_day

day_of_week
1     999238
2    1467002
3    1524623
4    1504311
5    1437269
6    1135170
7     769063
Name: page_loads, dtype: int64